name: Bandit Code Security

on: [push, pull_request]

permissions:
  contents: read
  security-events: write

jobs:
  bandit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: 3.9

      - name: Install Bandit
        shell: bash
        run: pip install bandit[sarif]

      - name: Scan
        shell: bash
        run: bandit -c bandit.yml -r -f sarif -o results.sarif app

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: results.sarif
