name: Bandit Code Security

on: [push, pull_request]

jobs:
  bandit:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python 3.9
          uses: actions/setup-python@v5
          with:
            python-version: 3.9
      - name: Install Bandit
        shell: bash
        run: pip install bandit[sarif]

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Scan
        shell: bash
        run: bandit -c bandit.yml -r -f sarif -o resulat.sarif .

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: results.sarif

    