name: Build iOS App

on:
  push:
    branches: [ main, master, standalone-testing ]
  pull_request:
    branches: [ main, master, standalone-testing ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install briefcase
        pip install toga
    
    - name: Create iOS app
      working-directory: ./standalone
      run: |
        briefcase create iOS
        briefcase build iOS
      env:
        XCODE_DEVELOPMENT_TEAM: ${{ secrets.XCODE_DEVELOPMENT_TEAM }}
    
    - name: Upload IPA
      uses: actions/upload-artifact@v4
      with:
        name: castle-ios
        path: standalone/build/castle/ios/xcode/build/Debug-iphonesimulator/Castle.app 