name: Build macOS App

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install briefcase
        pip install toga
    
    - name: Create macOS app
      working-directory: ./standalone
      run: |
        briefcase create macos
        briefcase build macos
    
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: castle-macos
        path: standalone/build/castle/macos/app/Castle.app 